INSERT INTO clickhouse.reports.stage_unified_sales
WITH raw_source AS (
    SELECT
        'clickhouse' AS source_system,
        source_file,
        id,
        customer_first_name,
        customer_last_name,
        customer_age,
        customer_email,
        customer_country,
        customer_postal_code,
        customer_pet_type,
        customer_pet_name,
        customer_pet_breed,
        seller_first_name,
        seller_last_name,
        seller_email,
        seller_country,
        seller_postal_code,
        product_name,
        product_category,
        product_price,
        product_quantity,
        sale_date,
        sale_customer_id,
        sale_seller_id,
        sale_product_id,
        sale_quantity,
        sale_total_price,
        store_name,
        store_location,
        store_city,
        store_state,
        store_country,
        store_phone,
        store_email,
        pet_category,
        product_weight,
        product_color,
        product_size,
        product_brand,
        product_material,
        product_description,
        product_rating,
        product_reviews,
        product_release_date,
        product_expiry_date,
        supplier_name,
        supplier_contact,
        supplier_email,
        supplier_phone,
        supplier_address,
        supplier_city,
        supplier_country
    FROM clickhouse.reports.stage_mock_data_raw
    UNION ALL
    SELECT
        'postgres' AS source_system,
        source_file,
        id,
        customer_first_name,
        customer_last_name,
        customer_age,
        customer_email,
        customer_country,
        customer_postal_code,
        customer_pet_type,
        customer_pet_name,
        customer_pet_breed,
        seller_first_name,
        seller_last_name,
        seller_email,
        seller_country,
        seller_postal_code,
        product_name,
        product_category,
        product_price,
        product_quantity,
        sale_date,
        sale_customer_id,
        sale_seller_id,
        sale_product_id,
        sale_quantity,
        sale_total_price,
        store_name,
        store_location,
        store_city,
        store_state,
        store_country,
        store_phone,
        store_email,
        pet_category,
        product_weight,
        product_color,
        product_size,
        product_brand,
        product_material,
        product_description,
        product_rating,
        product_reviews,
        product_release_date,
        product_expiry_date,
        supplier_name,
        supplier_contact,
        supplier_email,
        supplier_phone,
        supplier_address,
        supplier_city,
        supplier_country
    FROM postgresql.stage.mock_data_raw
),
typed AS (
    SELECT
        source_system,
        source_file,
        CAST(NULLIF(id, '') AS integer) AS source_id,
        NULLIF(customer_first_name, '') AS customer_first_name,
        NULLIF(customer_last_name, '') AS customer_last_name,
        CAST(NULLIF(customer_age, '') AS integer) AS customer_age,
        lower(NULLIF(customer_email, '')) AS customer_email,
        NULLIF(customer_country, '') AS customer_country,
        coalesce(NULLIF(customer_postal_code, ''), '') AS customer_postal_code,
        lower(NULLIF(customer_pet_type, '')) AS customer_pet_type,
        NULLIF(customer_pet_name, '') AS customer_pet_name,
        NULLIF(customer_pet_breed, '') AS customer_pet_breed,
        NULLIF(seller_first_name, '') AS seller_first_name,
        NULLIF(seller_last_name, '') AS seller_last_name,
        lower(NULLIF(seller_email, '')) AS seller_email,
        NULLIF(seller_country, '') AS seller_country,
        coalesce(NULLIF(seller_postal_code, ''), '') AS seller_postal_code,
        NULLIF(product_name, '') AS product_name,
        NULLIF(product_category, '') AS product_category,
        CAST(NULLIF(product_price, '') AS decimal(14, 2)) AS product_price,
        CAST(NULLIF(product_quantity, '') AS integer) AS product_quantity,
        CAST(date_parse(NULLIF(sale_date, ''), '%c/%e/%Y') AS date) AS sale_date,
        CAST(NULLIF(sale_customer_id, '') AS integer) AS sale_customer_id,
        CAST(NULLIF(sale_seller_id, '') AS integer) AS sale_seller_id,
        CAST(NULLIF(sale_product_id, '') AS integer) AS sale_product_id,
        CAST(NULLIF(sale_quantity, '') AS integer) AS sale_quantity,
        CAST(NULLIF(sale_total_price, '') AS decimal(14, 2)) AS sale_total_price,
        NULLIF(store_name, '') AS store_name,
        NULLIF(store_location, '') AS store_location,
        NULLIF(store_city, '') AS store_city,
        coalesce(NULLIF(store_state, ''), '') AS store_state,
        NULLIF(store_country, '') AS store_country,
        NULLIF(store_phone, '') AS store_phone,
        lower(NULLIF(store_email, '')) AS store_email,
        NULLIF(pet_category, '') AS pet_category,
        CAST(NULLIF(product_weight, '') AS decimal(12, 2)) AS product_weight,
        NULLIF(product_color, '') AS product_color,
        NULLIF(product_size, '') AS product_size,
        NULLIF(product_brand, '') AS product_brand,
        NULLIF(product_material, '') AS product_material,
        NULLIF(product_description, '') AS product_description,
        CAST(NULLIF(product_rating, '') AS double) AS product_rating,
        CAST(NULLIF(product_reviews, '') AS integer) AS product_reviews,
        CAST(date_parse(NULLIF(product_release_date, ''), '%c/%e/%Y') AS date) AS product_release_date,
        CAST(date_parse(NULLIF(product_expiry_date, ''), '%c/%e/%Y') AS date) AS product_expiry_date,
        NULLIF(supplier_name, '') AS supplier_name,
        NULLIF(supplier_contact, '') AS supplier_contact,
        lower(NULLIF(supplier_email, '')) AS supplier_email,
        NULLIF(supplier_phone, '') AS supplier_phone,
        NULLIF(supplier_address, '') AS supplier_address,
        NULLIF(supplier_city, '') AS supplier_city,
        NULLIF(supplier_country, '') AS supplier_country
    FROM raw_source
)
SELECT
    source_system,
    source_file,
    lower(to_hex(md5(to_utf8(concat_ws('|', source_system, source_file, CAST(source_id AS varchar)))))) AS sale_event_key,
    source_id,
    lower(to_hex(md5(to_utf8(customer_email)))) AS customer_key,
    sale_customer_id AS source_customer_id,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    lower(to_hex(md5(to_utf8(concat_ws('|', customer_pet_name, customer_pet_type, customer_pet_breed, pet_category))))) AS pet_key,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    pet_category,
    lower(to_hex(md5(to_utf8(seller_email)))) AS seller_key,
    sale_seller_id AS source_seller_id,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    lower(to_hex(md5(to_utf8(concat_ws('|', product_name, product_category, product_brand, product_material, product_color, product_size, CAST(product_weight AS varchar), product_description))))) AS product_key,
    sale_product_id AS source_product_id,
    product_name,
    product_category,
    product_price,
    product_quantity,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    sale_date,
    sale_quantity,
    sale_total_price,
    CAST(round(product_price * CAST(sale_quantity AS decimal(14, 2)), 2) AS decimal(14, 2)) AS calculated_total_amount,
    CASE WHEN abs(sale_total_price - product_price * CAST(sale_quantity AS decimal(14, 2))) <= DECIMAL '0.01' THEN 1 ELSE 0 END AS is_total_consistent,
    lower(to_hex(md5(to_utf8(store_email)))) AS store_key,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    lower(to_hex(md5(to_utf8(supplier_email)))) AS supplier_key,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM typed;
