connector.name=clickhouse
connection-url=jdbc:clickhouse://clickhouse:8123/reports
connection-user=lab
connection-password=lab
clickhouse.map-string-as-varchar=true
case-insensitive-name-matching=true
